version: "3.7"

x-common:
  - &DB_ROOTPASS "passw0rd"
  - &DB_PASS "redmine"
  - &DB_USER "redmine"
  - &DB_NAME "redmine"

services:
#  metabase:
#    #restart: always
#    image: metabase/metabase
#    depends_on:
#      - postgres
#    ports:
#      - "10081:3000"

  postgres:
    #restart: always
    image: kudoshunsuke/docker-redmica-db-postgres
    build:
      context: ./
      dockerfile: ./Dockerfile.postgres
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: *DB_PASS
      POSTGRES_USER: *DB_USER

  redmica:
    #restart: always
    image: kudoshunsuke/docker-redmica
    build:
      context: ./
      dockerfile: ./Dockerfile.redmica
    depends_on:
      - postgres
    ports:
      - "10080:80"
    environment:
      TZ: Asia/Tokyo
      DB_ADAPTER: postgresql
      DB_ENCODING: utf8
      DB_CHARSET: utf8
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: *DB_NAME
      DB_USER: *DB_USER
      DB_PASS: *DB_PASS
    entrypoint: /entrypoint.sh
    tty: true
    command: ["/usr/bin/supervisord", "-nc", "/etc/supervisor/supervisord.conf"]
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./assets:/assets:ro
      - ./supervisor/conf.d:/etc/supervisor/conf.d:ro
      - ./nginx/conf.d/default:/etc/nginx/sites-available/default:ro
      - ./plugins:/plugins:ro

  chupa-text-proxy:
    #restart: always
    image: groonga/chupa-text:proxy
    environment:
      TZ: Asia/Tokyo

  chupa-text:
    #restart: always
    image: groonga/chupa-text:ubuntu-latest
    depends_on:
      - chupa-text-proxy
    environment:
      TZ: Asia/Tokyo
      http_proxy: http://chupa-text-proxy:3128/
      https_proxy: http://chupa-text-proxy:3128/
      RAILS_SERVE_STATIC_FILES: "true"

volumes:
  postgres:
    driver: "local"

